name: CI-RSS

on:
  push:
  schedule:
  - cron: "* */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2
    - name: running curl
      run: curl https://1481505583477372.cn-hongkong.fc.aliyuncs.com/2016-08-15/proxy/hk-rss/hk-rss/list

